services:
  test_db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d test_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      POSTGRES_HOST: test_db
    depends_on:
      test_db:
        condition: service_healthy
